// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const AttackTypeSchema = z
    .enum([
        CONSTS.ATTACK_TYPE_MELEE,
        CONSTS.ATTACK_TYPE_RANGED,
    ])
    .describe('fields.attackType');

export type AttackType = z.infer<typeof AttackTypeSchema>;
