// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const CreatureSizeSchema = z
    .enum([
        CONSTS.CREATURE_SIZE_TINY,
        CONSTS.CREATURE_SIZE_SMALL,
        CONSTS.CREATURE_SIZE_MEDIUM,
        CONSTS.CREATURE_SIZE_LARGE,
        CONSTS.CREATURE_SIZE_HUGE,
        CONSTS.CREATURE_SIZE_GARGANTUAN,
    ])
    .describe('fields.creatureSize');

export type CreatureSize = z.infer<typeof CreatureSizeSchema>;
