// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const CreatureVisibilitySchema = z
    .enum([
        CONSTS.CREATURE_VISIBILITY_VISIBLE,
        CONSTS.CREATURE_VISIBILITY_INVISIBLE,
        CONSTS.CREATURE_VISIBILITY_BLINDED,
        CONSTS.CREATURE_VISIBILITY_HIDDEN,
        CONSTS.CREATURE_VISIBILITY_DARKNESS,
    ])
    .describe('fields.creatureVisibility');

export type CreatureVisibility = z.infer<typeof CreatureVisibilitySchema>;
