// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const DamageTypeSchema = z
    .enum([
        CONSTS.DAMAGE_TYPE_SLASHING,
        CONSTS.DAMAGE_TYPE_CRUSHING,
        CONSTS.DAMAGE_TYPE_PIERCING,
        CONSTS.DAMAGE_TYPE_THERMAL,
        CONSTS.DAMAGE_TYPE_CRYOGENIC,
        CONSTS.DAMAGE_TYPE_CHEMICAL,
        CONSTS.DAMAGE_TYPE_ELECTRIC,
    ])
    .describe('fields.damageType');

export type DamageType = z.infer<typeof DamageTypeSchema>;
