// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const DistanceSchema = z
    .enum([
        CONSTS.DISTANCE_CLOSE,
        CONSTS.DISTANCE_MEDIUM,
        CONSTS.DISTANCE_FAR,
    ])
    .describe('fields.distance');

export type Distance = z.infer<typeof DistanceSchema>;
