// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const EffectSubtypeSchema = z
    .enum([
        CONSTS.EFFECT_SUBTYPE_MAGICAL,
        CONSTS.EFFECT_SUBTYPE_EXTRAORDINARY,
        CONSTS.EFFECT_SUBTYPE_SUPERNATURAL,
        CONSTS.EFFECT_SUBTYPE_UNYIELDING,
        CONSTS.EFFECT_SUBTYPE_WEAPON,
    ])
    .describe('fields.effectSubtype');

export type EffectSubtype = z.infer<typeof EffectSubtypeSchema>;
