// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const EffectTypeSchema = z
    .enum([
        CONSTS.EFFECT_ABILITY_MODIFIER,
        CONSTS.EFFECT_ARMOR_CLASS_MODIFIER,
        CONSTS.EFFECT_BLINDNESS,
        CONSTS.EFFECT_DARKVISION,
        CONSTS.EFFECT_INVISIBILITY,
        CONSTS.EFFECT_LIGHT,
        CONSTS.EFFECT_REGENERATION,
        CONSTS.EFFECT_SEE_INVISIBILITY,
        CONSTS.EFFECT_STEALTH,
    ])
    .describe('fields.effectType');

export type EffectType = z.infer<typeof EffectTypeSchema>;
