// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const EnvironmentSchema = z
    .enum([
        CONSTS.ENVIRONMENT_DARKNESS,
        CONSTS.ENVIRONMENT_FOG,
        CONSTS.ENVIRONMENT_RAIN,
        CONSTS.ENVIRONMENT_UNDERWATER,
        CONSTS.ENVIRONMENT_WIND,
        CONSTS.ENVIRONMENT_DIFFICULT_TERRAIN,
    ])
    .describe('fields.environment');

export type Environment = z.infer<typeof EnvironmentSchema>;
