// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const EquipmentSlotSchema = z
    .enum([
        CONSTS.EQUIPMENT_SLOT_INVALID,
        CONSTS.EQUIPMENT_SLOT_HEAD,
        CONSTS.EQUIPMENT_SLOT_NECK,
        CONSTS.EQUIPMENT_SLOT_CHEST,
        CONSTS.EQUIPMENT_SLOT_BACK,
        CONSTS.EQUIPMENT_SLOT_ARMS,
        CONSTS.EQUIPMENT_SLOT_WEAPON_MELEE,
        CONSTS.EQUIPMENT_SLOT_WEAPON_RANGED,
        CONSTS.EQUIPMENT_SLOT_NATURAL_WEAPON_1,
        CONSTS.EQUIPMENT_SLOT_NATURAL_WEAPON_2,
        CONSTS.EQUIPMENT_SLOT_NATURAL_WEAPON_3,
        CONSTS.EQUIPMENT_SLOT_SHIELD,
        CONSTS.EQUIPMENT_SLOT_FINGER_LEFT,
        CONSTS.EQUIPMENT_SLOT_FINGER_RIGHT,
        CONSTS.EQUIPMENT_SLOT_AMMO,
        CONSTS.EQUIPMENT_SLOT_WAIST,
        CONSTS.EQUIPMENT_SLOT_FEET,
    ])
    .describe('fields.equipmentSlot');

export type EquipmentSlot = z.infer<typeof EquipmentSlotSchema>;
