// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const EquipItemOutcomeSchema = z
    .enum([
        CONSTS.EQUIP_ITEM_SUCCESS,
        CONSTS.EQUIP_ITEM_FAILURE_REASON_NO_SUITABLE_SLOT,
        CONSTS.EQUIP_ITEM_FAILURE_REASON_ALREADY_EQUIPPED,
        CONSTS.EQUIP_ITEM_FAILURE_REASON_CURSED_SLOT,
        CONSTS.EQUIP_ITEM_FAILURE_REASON_REQUIREMENTS,
        CONSTS.EQUIP_ITEM_FAILURE_REASON_NOT_EQUIPPED,
    ])
    .describe('fields.equipItemOutcome');

export type EquipItemOutcome = z.infer<typeof EquipItemOutcomeSchema>;
