// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const ImmunitySchema = z
    .enum([
        CONSTS.IMMUNITY_TYPE_CHARM,
        CONSTS.IMMUNITY_TYPE_DISEASE,
        CONSTS.IMMUNITY_TYPE_FEAR,
        CONSTS.IMMUNITY_TYPE_PARALYSIS,
        CONSTS.IMMUNITY_TYPE_PETRIFICATION,
        CONSTS.IMMUNITY_TYPE_POISON,
        CONSTS.IMMUNITY_TYPE_ROOT,
        CONSTS.IMMUNITY_TYPE_STUN,
        CONSTS.IMMUNITY_TYPE_BLINDNESS,
        CONSTS.IMMUNITY_TYPE_CRITICAL_HIT,
    ])
    .describe('fields.immunity');

export type Immunity = z.infer<typeof ImmunitySchema>;
