// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const ProficiencySchema = z
    .enum([
        CONSTS.PROFICIENCY_WEAPON_SIMPLE,
        CONSTS.PROFICIENCY_WEAPON_COMPLEX,
        CONSTS.PROFICIENCY_WEAPON_EXPERT,
        CONSTS.PROFICIENCY_WEAPON_MAGIC,
        CONSTS.PROFICIENCY_WEAPON_TECHNOLOGIC,
        CONSTS.PROFICIENCY_UNARMED,
        CONSTS.PROFICIENCY_ARMOR_LIGHT,
        CONSTS.PROFICIENCY_ARMOR_MEDIUM,
        CONSTS.PROFICIENCY_ARMOR_HEAVY,
        CONSTS.PROFICIENCY_SHIELD,
    ])
    .describe('fields.proficiency');

export type Proficiency = z.infer<typeof ProficiencySchema>;
