// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const PropertyTypeSchema = z
    .enum([
        CONSTS.PROPERTY_ABILITY_MODIFIER,
        CONSTS.PROPERTY_ARMOR_CLASS_MODIFIER,
        CONSTS.PROPERTY_DARKVISION,
        CONSTS.PROPERTY_LIGHT,
        CONSTS.PROPERTY_REGENERATION,
    ])
    .describe('fields.propertyType');

export type PropertyType = z.infer<typeof PropertyTypeSchema>;
