// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const SkillSchema = z
    .enum([
        CONSTS.SKILL_ACROBATICS,
        CONSTS.SKILL_ALCHEMY,
        CONSTS.SKILL_ARCANA,
        CONSTS.SKILL_ATHLETICS,
        CONSTS.SKILL_AURA,
        CONSTS.SKILL_DISCIPLINE,
        CONSTS.SKILL_FAITH,
        CONSTS.SKILL_HAGGLE,
        CONSTS.SKILL_INVESTIGATION,
        CONSTS.SKILL_MARTIAL_EXPERTISE,
        CONSTS.SKILL_PERCEPTION,
        CONSTS.SKILL_PERSUASION,
        CONSTS.SKILL_SLEIGHT_OF_HAND,
        CONSTS.SKILL_STEALTH,
        CONSTS.SKILL_SURVIVAL,
        CONSTS.SKILL_TECHNOLOGY,
    ])
    .describe('fields.skill');

export type Skill = z.infer<typeof SkillSchema>;
