// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const SpecieSchema = z
    .enum([
        CONSTS.SPECIE_ABERRATION,
        CONSTS.SPECIE_BEAST,
        CONSTS.SPECIE_CELESTIAL,
        CONSTS.SPECIE_CONSTRUCT,
        CONSTS.SPECIE_DRAGON,
        CONSTS.SPECIE_ELEMENTAL,
        CONSTS.SPECIE_FEY,
        CONSTS.SPECIE_FIEND,
        CONSTS.SPECIE_GIANT,
        CONSTS.SPECIE_HUMANOID,
        CONSTS.SPECIE_MONSTROSITY,
        CONSTS.SPECIE_OOZE,
        CONSTS.SPECIE_PLANT,
        CONSTS.SPECIE_UNDEAD,
    ])
    .describe('fields.specie');

export type Specie = z.infer<typeof SpecieSchema>;
