// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const ThreatSchema = z
    .enum([
        CONSTS.THREAT_PARALYSIS,
        CONSTS.THREAT_STUN,
        CONSTS.THREAT_DISEASE,
        CONSTS.THREAT_POISON,
        CONSTS.THREAT_BLAST,
        CONSTS.THREAT_BLINDNESS,
        CONSTS.THREAT_FEAR,
        CONSTS.THREAT_CHARM,
        CONSTS.THREAT_SPELL,
        CONSTS.THREAT_DEVICE,
        CONSTS.THREAT_PETRIFY,
    ])
    .describe('fields.threat');

export type Threat = z.infer<typeof ThreatSchema>;
