// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const ThreatTypeSchema = z
    .enum([
        CONSTS.THREAT_TYPE_BODY_DECAY,
        CONSTS.THREAT_TYPE_CHARM,
        CONSTS.THREAT_TYPE_DISEASE,
        CONSTS.THREAT_TYPE_FEAR,
        CONSTS.THREAT_TYPE_PARALYSIS,
        CONSTS.THREAT_TYPE_PETRIFICATION,
        CONSTS.THREAT_TYPE_POISON,
        CONSTS.THREAT_TYPE_SPELL,
    ])
    .describe('fields.threatType');

export type ThreatType = z.infer<typeof ThreatTypeSchema>;
