// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const ThreatTypeSchema = z
    .enum([
    ])
    .describe('fields.threatType');

export type ThreatType = z.infer<typeof ThreatTypeSchema>;
