// File generated by build-enum-schemas.sh

import z from 'zod';
import { CONSTS } from '../../consts';

export const WeaponAttributeSchema = z
    .enum([
        CONSTS.WEAPON_ATTRIBUTE_AMMUNITION,
        CONSTS.WEAPON_ATTRIBUTE_FINESSE,
        CONSTS.WEAPON_ATTRIBUTE_LOADING,
        CONSTS.WEAPON_ATTRIBUTE_SPECIAL,
        CONSTS.WEAPON_ATTRIBUTE_TWO_HANDED,
        CONSTS.WEAPON_ATTRIBUTE_VERSATILE,
        CONSTS.WEAPON_ATTRIBUTE_RANGED,
        CONSTS.WEAPON_ATTRIBUTE_SEMIAUTOMATIC,
        CONSTS.WEAPON_ATTRIBUTE_SPREAD,
    ])
    .describe('fields.weaponAttribute');

export type WeaponAttribute = z.infer<typeof WeaponAttributeSchema>;
