// File generated by build-disease-index.sh

import { DiseaseDefinitionSchema } from '../../schemas/Disease';
import type { Disease } from '../../schemas/enums/Disease';
import type { z } from 'zod';
import { CONSTS } from '../../consts';
import ghoulFever from './ghoul-fever.json';
import mummyRot from './mummy-rot.json';
import ratSickness from './rat-sickness.json';

export type DiseaseDefinition = z.infer<typeof DiseaseDefinitionSchema>;

const DISEASES: Record<Disease, DiseaseDefinition> = {
    [CONSTS.DISEASE_GHOUL_FEVER]: DiseaseDefinitionSchema.parse(ghoulFever),
    [CONSTS.DISEASE_MUMMY_ROT]: DiseaseDefinitionSchema.parse(mummyRot),
    [CONSTS.DISEASE_RAT_SICKNESS]: DiseaseDefinitionSchema.parse(ratSickness),
};

export default DISEASES;
