export const VARS = {
    HITPOINTS_PER_BODY: 8,
    HITPOINTS_BASE_VALUE: 20,
    ARMOR_CLASS_BASE_VALUE: 8,
    DAMAGE_FACTOR_IMMUNITY: 0,
    DAMAGE_FACTOR_RESISTANCE: 0.5,
    DAMAGE_FACTOR_VULNERABILITY: 2,
};
