// File generated by build-properties-index.sh
import z from 'zod';
import { PropertySchemaAbilityModifier } from './ability-modifier';
import { PropertySchemaRegeneration } from './regeneration';

export const PropertySchema = z.discriminatedUnion('type', [
    PropertySchemaAbilityModifier,
    PropertySchemaRegeneration,
]);

export type Property = z.infer<typeof PropertySchema>;
